### ISSUE TITLE
Modpack Request - more config - Crash when loading

### ISSUE THREAD

**Issue by Sngop** [AstroInteractive/DiscordSuite#53] opened 2018-06-29 16:02 UTC
## Modpack Request
can u add [SevTech ages](https://minecraft.curseforge.com/projects/sevtech-ages) modpack 
Project ID:268208
I **think** my game crash when I use it because of that

 ## Enhancement
it will be better if there a config file that lets us change everything in the Rich Presence ( if that possible )
for ex: change the icon of the modpack, or change the overworld img

##  Issues
**Crash when loading pack**

```
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from DiscordSuite (discordsuite)
Caused by: java.lang.NullPointerException
	at com.astro.discordsuite.integration.ModpackHandler.getModpack(ModpackHandler.java:16)
	at com.astro.discordsuite.Client.updatePresence(Client.java:39)
	at com.astro.discordsuite.DiscordSuite.construction(DiscordSuite.java:177)
```

full [crash_log](https://pastebin.com/fWUgF6zb)

**Comment by TheCodedOne** [comment] 2018-06-29 16:14
No, No, and duplicate of #41 

SevTech does not use discordsuite, image integration is limited to packs that include discordsuite due to the limited amount of images i am allowed to use.

Images cannot be customized by the user because discord limitation, i need to manually upload them.

**Closed by TheCodedOne** 2018-06-29 16:14 UTC
